import { lazy, type ComponentType, type LazyExoticComponent } from 'react'

export type Topic = {
  slug: string
  n: string
  title: string
  kicker: string
  blurb: string
  gopher?: string
  group: string
  page?: LazyExoticComponent<ComponentType>
}

export const topics: Topic[] = [
  {
    slug: 'scheduler',
    group: 'Runtime',
    n: '01',
    title: 'GMP scheduler',
    kicker: 'runtime/proc.go',
    gopher: 'convict-working-hard',
    blurb: 'How millions of goroutines share a few threads, and who runs next.',
    page: lazy(() => import('./gmp/Page')),
  },
  {
    slug: 'maps',
    group: 'Runtime',
    n: '02',
    title: 'Maps & Swiss tables',
    kicker: 'internal/runtime/maps',
    gopher: 'adventure-hiking',
    blurb: 'How a Go map finds a key fast, grows, and why it panics on concurrent writes.',
    page: lazy(() => import('./maps/Page')),
  },
  {
    slug: 'gc',
    group: 'Runtime',
    n: '03',
    title: 'Garbage collection',
    kicker: 'runtime/mgc.go',
    gopher: 'fairy-tale-witch-broom',
    blurb: 'How Go finds garbage while your program keeps running, and how to tune it.',
    page: lazy(() => import('./gc/Page')),
  },
  {
    slug: 'memory-layout',
    group: 'Runtime',
    n: '04',
    title: 'Padding & false sharing',
    kicker: 'memory layout',
    gopher: 'adventure-pirate-boat',
    blurb: 'Why field order changes a struct’s size, and how neighbouring counters slow each other.',
    page: lazy(() => import('./memorylayout/Page')),
  },
  {
    slug: 'slices',
    group: 'Language',
    n: '05',
    title: 'Slices & strings',
    kicker: 'runtime/slice.go',
    gopher: 'adventure-pushing-cart',
    blurb: 'Why append sometimes changes another slice, and what a string really is.',
    page: lazy(() => import('./slices/Page')),
  },
  {
    slug: 'interfaces',
    group: 'Language',
    n: '06',
    title: 'Interfaces & nil',
    kicker: 'runtime/iface.go',
    gopher: 'arts-ballet',
    blurb: 'Why an interface holding a nil pointer is not nil.',
    page: lazy(() => import('./interfaces/Page')),
  },
  {
    slug: 'defer',
    group: 'Language',
    n: '07',
    title: 'defer, panic & recover',
    kicker: 'defer · panic · recover',
    gopher: 'science-experiment-mishap',
    blurb: 'When defers run, what they copy, and which crashes recover can’t stop.',
    page: lazy(() => import('./defer/Page')),
  },
  {
    slug: 'generics',
    group: 'Language',
    n: '08',
    title: 'Generics & GC shapes',
    kicker: 'type parameters',
    gopher: 'fairy-tale-witch-cooking',
    blurb: 'Constraints, inference, and why *User and *Order share one compiled copy.',
    page: lazy(() => import('./generics/Page')),
  },
  {
    slug: 'channels',
    group: 'Concurrency',
    n: '09',
    title: 'Channels & select',
    kicker: 'runtime/chan.go',
    gopher: 'fairy-tale-messenger-red-letter',
    blurb: 'Handshakes, mailboxes, closed channels, select, and deadlocks.',
    page: lazy(() => import('./channels/Page')),
  },
  {
    slug: 'sync',
    group: 'Concurrency',
    n: '10',
    title: 'sync & data races',
    kicker: 'sync, sync/atomic',
    gopher: 'adventure-pirate-sword',
    blurb: 'Two goroutines, one counter: races, mutexes and atomics.',
    page: lazy(() => import('./sync/Page')),
  },
  {
    slug: 'memory-model',
    group: 'Concurrency',
    n: '11',
    title: 'The Go memory model',
    kicker: 'happens-before',
    gopher: 'science-lightbulb',
    blurb: 'When one goroutine is guaranteed to see another’s write, and what breaks without it.',
    page: lazy(() => import('./memorymodel/Page')),
  },
  {
    slug: 'patterns',
    group: 'Concurrency',
    n: '12',
    title: 'context & concurrency patterns',
    kicker: 'context, errgroup',
    gopher: 'science-power-to-the-masses',
    blurb: 'Cancel work with context, and share it out with worker pools.',
    page: lazy(() => import('./patterns/Page')),
  },
  {
    slug: 'indexes',
    group: 'Databases',
    n: '13',
    title: 'Indexes & query plans',
    kicker: 'postgres',
    gopher: 'fairy-tale-witch-learning',
    blurb: 'How an index turns a full-table scan into a quick lookup, and when it doesn’t.',
    page: lazy(() => import('./indexes/Page')),
  },
  {
    slug: 'transactions',
    group: 'Databases',
    n: '14',
    title: 'Transactions & isolation',
    kicker: 'postgres MVCC',
    gopher: 'fairy-tale-princess',
    blurb: 'What two transactions can see of each other, and how to avoid lost updates.',
    page: lazy(() => import('./transactions/Page')),
  },
  {
    slug: 'mongo-vs-postgres',
    group: 'Databases',
    n: '15',
    title: 'Postgres vs MongoDB',
    kicker: 'sql vs documents',
    gopher: 'fairy-tale-king',
    blurb: 'Tables or documents: what each is good at, and how to choose.',
    page: lazy(() => import('./mongo/Page')),
  },
  {
    slug: 'kafka',
    group: 'Backend',
    n: '16',
    title: 'Kafka & delivery guarantees',
    kicker: 'messaging',
    gopher: 'adventure-pirate-lifting-goods',
    blurb: 'Partitions, consumer groups, and why messages can arrive twice.',
    page: lazy(() => import('./kafka/Page')),
  },
  {
    slug: 'queues',
    group: 'Backend',
    n: '17',
    title: 'Kafka vs SQS vs Pub/Sub',
    kicker: 'log vs queue',
    gopher: 'fairy-tale-messenger-running',
    blurb: 'A log you reread versus a queue you drain, and which to pick.',
    page: lazy(() => import('./queues/Page')),
  },
  {
    slug: 'http',
    group: 'Backend',
    n: '18',
    title: 'HTTP, TLS & gRPC',
    kicker: 'net/http',
    gopher: 'fairy-tale-messenger-showing',
    blurb: 'What happens between typing a URL and getting a response.',
    page: lazy(() => import('./http/Page')),
  },
  {
    slug: 'scaling',
    group: 'Backend',
    n: '19',
    title: 'Scaling & resilience',
    kicker: 'architecture',
    gopher: 'superhero-lifting-1TB',
    blurb: 'Caches, retries and circuit breakers that keep a service up under load.',
    page: lazy(() => import('./scaling/Page')),
  },
  {
    slug: 'profiling',
    group: 'Backend',
    n: '20',
    title: 'Profiling & observability',
    kicker: 'pprof, metrics',
    gopher: 'science-welding',
    blurb: 'Find the slow code with pprof, and watch a service with metrics.',
    page: lazy(() => import('./profiling/Page')),
  },
  {
    slug: 'clocks',
    group: 'Distributed systems',
    n: '21',
    title: 'Clocks & ordering',
    kicker: 'lamport · hlc',
    gopher: 'fairy-tale-witch-old',
    blurb: 'Why timestamps can’t order events across machines, and what to use instead.',
    page: lazy(() => import('./clocks/Page')),
  },
  {
    slug: 'consistency',
    group: 'Distributed systems',
    n: '22',
    title: 'Consistency models & CAP',
    kicker: 'linearizability',
    gopher: 'science-lightbulb',
    blurb: 'What “consistent” really means, and what CAP and PACELC actually promise.',
    page: lazy(() => import('./consistency/Page')),
  },
  {
    slug: 'replication',
    group: 'Distributed systems',
    n: '23',
    title: 'Replication & quorums',
    kicker: 'leaders · quorums',
    gopher: 'friends-hugging-docker',
    blurb: 'How copies drift apart, and how quorums and conflict rules bring them back.',
    page: lazy(() => import('./replication/Page')),
  },
  {
    slug: 'consensus',
    group: 'Distributed systems',
    n: '24',
    title: 'Consensus & Raft',
    kicker: 'raft',
    gopher: 'fairy-tale-armored-knight',
    blurb: 'How a cluster elects a leader and agrees on one log despite crashes.',
    page: lazy(() => import('./consensus/Page')),
  },
  {
    slug: 'locks',
    group: 'Distributed systems',
    n: '25',
    title: 'Locks, leases & fencing',
    kicker: 'fencing tokens',
    gopher: 'convict-chained',
    blurb: 'Why a lock with a timeout isn’t safe, and how fencing tokens fix it.',
    page: lazy(() => import('./locks/Page')),
  },
  {
    slug: 'failure-detection',
    group: 'Distributed systems',
    n: '26',
    title: 'Failure detection & partitions',
    kicker: 'heartbeats · gossip',
    gopher: 'dandy-raining',
    blurb: 'Slow or dead? Heartbeats, gossip, gray failures and split brain.',
    page: lazy(() => import('./failure-detection/Page')),
  },
  {
    slug: 'sharding',
    group: 'Distributed systems',
    n: '27',
    title: 'Sharding & consistent hashing',
    kicker: 'hash ring',
    gopher: 'adventure-pirate-boat',
    blurb: 'Spreading data over nodes without reshuffling everything when one changes.',
    page: lazy(() => import('./sharding/Page')),
  },
  {
    slug: 'dist-transactions',
    group: 'Distributed systems',
    n: '28',
    title: 'Sagas, 2PC & outbox',
    kicker: 'distributed transactions',
    gopher: 'fairy-tale-messenger-reading',
    blurb: 'Keeping several services consistent without one shared transaction.',
    page: lazy(() => import('./dist-transactions/Page')),
  },
  {
    slug: 'resilience',
    group: 'Distributed systems',
    n: '29',
    title: 'Timeouts, retries & breakers',
    kicker: 'resilience patterns',
    gopher: 'superhero-standing',
    blurb: 'Deadlines, backoff, breakers and load shedding that stop cascading failures.',
    page: lazy(() => import('./resilience/Page')),
  },
  {
    slug: 'tcp',
    group: 'Networking',
    n: '30',
    title: 'TCP edge cases',
    kicker: 'tcp',
    gopher: 'adventure-pushing-cart',
    blurb: 'TIME_WAIT, backlogs, Nagle, resets, and connections that die silently.',
    page: lazy(() => import('./tcp/Page')),
  },
  {
    slug: 'dns-lb',
    group: 'Networking',
    n: '31',
    title: 'DNS & load balancers',
    kicker: 'dns · l4 · l7',
    gopher: 'fairy-tale-robin-hood',
    blurb: 'Caching, ndots, idle timeouts, and why gRPC defeats L4 balancing.',
    page: lazy(() => import('./dns-lb/Page')),
  },
  {
    slug: 'tls-quic',
    group: 'Networking',
    n: '32',
    title: 'TLS & QUIC edge cases',
    kicker: 'tls · quic · mtu',
    gopher: 'fairy-tale-messenger-showing',
    blurb: '0-RTT replay, broken chains, MTU black holes, and what QUIC changes.',
    page: lazy(() => import('./tls-quic/Page')),
  },
  {
    slug: 'syscalls',
    group: 'OS & hardware',
    n: '33',
    title: 'Syscalls & kernel mode',
    kicker: 'user vs kernel',
    gopher: 'superhero-getting-ready',
    blurb: 'Why the kernel is walled off, and what crossing the wall costs.',
    page: lazy(() => import('./syscalls/Page')),
  },
  {
    slug: 'virtual-memory',
    group: 'OS & hardware',
    n: '34',
    title: 'Virtual memory',
    kicker: 'page tables · mmap',
    gopher: 'adventure-hiking',
    blurb: 'Page tables, page faults, mmap, and why RSS isn’t what you allocated.',
    page: lazy(() => import('./virtual-memory/Page')),
  },
  {
    slug: 'os-scheduling',
    group: 'OS & hardware',
    n: '35',
    title: 'Threads & CPU scheduling',
    kicker: 'futex · cfs · cgroups',
    gopher: 'science-jetpack',
    blurb: 'Context switches, futexes, cgroup throttling, and what load average means.',
    page: lazy(() => import('./os-scheduling/Page')),
  },
  {
    slug: 'os-io',
    group: 'OS & hardware',
    n: '36',
    title: 'I/O: page cache & epoll',
    kicker: 'epoll · io_uring · fsync',
    gopher: 'arts-saxophone',
    blurb: 'Blocking, readiness and completion I/O, the page cache, and what fsync promises.',
    page: lazy(() => import('./os-io/Page')),
  },
  {
    slug: 'containers',
    group: 'OS & hardware',
    n: '37',
    title: 'Containers under the hood',
    kicker: 'namespaces · cgroups',
    gopher: 'friends-docker',
    blurb: 'Namespaces, cgroups, OOM kills, and why PID 1 is special.',
    page: lazy(() => import('./containers/Page')),
  },
  {
    slug: 'cpu-caches',
    group: 'OS & hardware',
    n: '38',
    title: 'CPU caches & memory ordering',
    kicker: 'mesi · numa',
    gopher: 'science-welding',
    blurb: 'Cache lines, coherence, NUMA, and why other cores see writes late.',
    page: lazy(() => import('./cpu-caches/Page')),
  },
]

export const liveTopics = topics.filter((t) => t.page)
export const groups = [...new Set(topics.map((t) => t.group))]
